import { OpenApiBuilder, OpenAPIObject, PathItemObject } from "openapi3-ts";
import HAR from "../../models/HAR";
import ApiSpecBuilder from "../../services/ApiSpecBuilder";
import { copyToClipboard, saveJSON } from "../../utils/io";


export default class SwaggerState {
 
  openApiV3Builder = ApiSpecBuilder.createOpenApiV3();
  requests: HAR[] = [];

  host: string = "";
  ouputSpec: OpenAPIObject = OpenApiBuilder.create().getSpec();

  loading = false;

  setHost(host) {
    this.host = host;
  }

  setRequests(requests) {
    this.requests = requests;
    this._rebuildOpenApiSpec();
  }

  setLoading(loading: boolean) {
    this.loading = loading;
  }

  saveDoc() {
    const json = JSON.stringify(this.ouputSpec, null, 2);
    saveJSON(json, `${this.host}-openapi.json`);
  }

  clipboardCopy() {
    const json = JSON.stringify(this.ouputSpec, null, 2);
    copyToClipboard(json);
  }

  _rebuildOpenApiSpec() {
    if (!this.requests?.length) {
      this.ouputSpec = OpenApiBuilder.create().getSpec();
      return
    }

    const baseUrls = ApiSpecBuilder.getBaseUrls(this.requests).map(x => x.url);
    this.ouputSpec = this.openApiV3Builder.build({
      title: `${this.host} OpenApi specification`,
      description: 'Generated by ReSpecT',
      baseUrls,
      requests: this.requests
    });
  }
}
